name: freelancer_assistant
description: A Freelancer Assistant app with Gemini AI integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-24.0.dev

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env  # If using assets folder
    - .env         # If in project root
  generate: true